[workspace]
name = "crs-workspace"
version = "0.1.0"
description = "Molecular Crystal Structure Prediction Suite"
authors = ["Pedro Juan Royo <pedro.juan.royo@google.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64"]

[dependencies]
rust = ">=1.96.0"
clang = "*"
make = "*"

[tasks]
build = "cargo build --all"
test = "cargo test --all"
format = "cargo fmt --all"